./exp_compiler.sh o hh device_set/hh/qaoa/8_0_gs_d.json qaoa 8 2
./exp_compiler.sh o hh device_set/hh/qaoa/8_0_gs_d.json qaoa 8 6
./exp_compiler.sh o grid device_set/grid/qaoa/8_0_gs_d.json qaoa 8 6
./exp_compiler.sh o hh device_set/hh/qaoa/8_0_gs_d.json qaoa 8 7
./exp_compiler.sh o grid device_set/grid/qaoa/8_0_gs_d.json qaoa 8 7  
./exp_compiler.sh o hh device_set/hh/qaoa/8_0_gs_d.json qaoa 8 8
./exp_compiler.sh o grid device_set/grid/qaoa/8_0_gs_d.json qaoa 8 8
./exp_compiler.sh o hh device_set/hh/qaoa/8_0_gs_d.json qaoa 8 9
./exp_compiler.sh o grid device_set/grid/qaoa/8_0_gs_d.json qaoa 8 9  
./exp_compiler.sh o hh device_set/hh/qaoa/8_0_gs_d.json qaoa 8 10
./exp_compiler.sh o grid device_set/grid/qaoa/8_0_gs_d.json qaoa 8 10
./exp_compiler.sh o hh device_set/hh/qaoa/8_0_gs_d.json qaoa 8 11
./exp_compiler.sh o grid device_set/grid/qaoa/8_0_gs_d.json qaoa 8 11
./exp_compiler.sh o hh device_set/hh/qaoa/8_0_gs_d.json qaoa 8 12
./exp_compiler.sh o grid device_set/grid/qaoa/8_0_gs_d.json qaoa 8 12
./exp_compiler.sh o hh device_set/hh/qaoa/8_0_gs_d.json qaoa 8 13
./exp_compiler.sh o grid device_set/grid/qaoa/8_0_gs_d.json qaoa 8 13
./exp_compiler.sh o hh device_set/hh/qaoa/8_0_gs_d.json qaoa 8 14
./exp_compiler.sh o grid device_set/grid/qaoa/8_0_gs_d.json qaoa 8 14
./exp_compiler.sh o hh device_set/hh/qaoa/8_0_gs_d.json qaoa 8 15
./exp_compiler.sh o grid device_set/grid/qaoa/8_0_gs_d.json qaoa 8 15
